<a href="https://colab.research.google.com/github/wasam0110/ArtificialNueralNetworkLab/blob/main/ANNlab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world'")

hello world'


In [ ]:
import torch
import numpy as np
torch.__version__

'2.8.0+cu126'

In [ ]:
torch.tensor([[1,2,3],[4,5,6]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
torch.zeros((3,5))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.eye(4)


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [ ]:
torch.randint(0, 100, (3, 3))


tensor([[85, 84,  2],
        [43, 35, 82],
        [90, 37, 82]])

In [ ]:
torch.rand(5)

tensor([0.9098, 0.3435, 0.3203, 0.4712, 0.0219])

In [ ]:
t = torch.rand((3,3), dtype=torch.float32)
print(t.numpy())

[[0.25376296 0.7090986  0.85693365]
 [0.6185586  0.5390034  0.9611539 ]
 [0.40204966 0.11977613 0.84895957]]


In [ ]:

# random float array (0 to 1)
b = np.random.rand(3,3)

# random int array (1 to 10)
a = np.random.randint(1, 10, (3,3))
print(b)
print(a)
torch.from_numpy(n)

[[0.79157168 0.0083081  0.56321843]
 [0.16413643 0.25952425 0.60267721]
 [0.92346148 0.08656045 0.42643776]]
[[9 3 7]
 [6 7 3]
 [4 7 1]]


tensor([[0.5723, 0.0364, 0.8071],
        [0.4165, 0.0193, 0.1749],
        [0.6787, 0.2869, 0.5977]], dtype=torch.float16)

In [ ]:
torch.ones((3,3)) +torch.eye(3)

tensor([[2., 1., 1.],
        [1., 2., 1.],
        [1., 1., 2.]])

In [ ]:
t = torch.rand((3,3))
t.shape

torch.Size([3, 3])

In [ ]:
t = torch.rand((3,3))
t.device

device(type='cpu')

In [ ]:
x = torch.randn(4,5)
y = torch.ones(x.size(0),3)
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
torch.randint(1,2,(7,3))

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])